### ISSUE TITLE
PackageRetreivalTask failing as it does not appear to be reading repositoryPath correctly

### ISSUE THREAD

**Issue by delradie** [baseclass/Contrib.Nuget#56]
When compiling our solution a windows forms project (using packages.config) that references a nuget package that depends on Baseclass.Contrib.Nuget.Output is throwing the following error. Having read through the code on here I noticed the system expects the nuget.config to be in the same directory as the solution. I have added a nuget.config in this directory with the following section`  <config>
     <add key="repositorypath" value=".packages" />
   </config>`

Despite this it seems to be looking for a directory "packages", despite us using ".packages" (the parent directory appears to be correct) meaning we get this error when building:

`42>"E:\KK\src\User Experience\Platform Tools\KKBO\KnowledgeKube.BackOffice.csproj" (Build;BuiltProjectOutputGroup;BuiltProjectOutputGroupDependencies;DebugSymbolsProjectOutputGroup;DebugSymbolsProjectOutputGroupDependencies;DocumentationProjectOutputGroup;DocumentationProjectOutputGroupDependencies;SatelliteDllsProjectOutputGroup;SatelliteDllsProjectOutputGroupDependencies;SGenFilesOutputGroup;SGenFilesOutputGroupDependencies target) (1) ->
42>(CollectNugetOutputFiles target) -> 
42>  E:\KK\src\.packages\Baseclass.Contrib.Nuget.Output.2.4.3\build\Baseclass.Contrib.Nuget.Output.targets(65,5): error MSB4018: The "PackageRetrievalTask" task failed unexpectedly.
42>E:\KK\src\.packages\Baseclass.Contrib.Nuget.Output.2.4.3\build\Baseclass.Contrib.Nuget.Output.targets(65,5): error MSB4018: System.IO.DirectoryNotFoundException: Could not find a part of the path 'E:\KK\src\packages'.
42>E:\KK\src\.packages\Baseclass.Contrib.Nuget.Output.2.4.3\build\Baseclass.Contrib.Nuget.Output.targets(65,5): error MSB4018:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
42>E:\KK\src\.packages\Baseclass.Contrib.Nuget.Output.2.4.3\build\Baseclass.Contrib.Nuget.Output.targets(65,5): error MSB4018:    at System.IO.FileSystemEnumerableIterator`1.CommonInit()
42>E:\KK\src\.packages\Baseclass.Contrib.Nuget.Output.2.4.3\build\Baseclass.Contrib.Nuget.Output.targets(65,5): error MSB4018:    at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
42>E:\KK\src\.packages\Baseclass.Contrib.Nuget.Output.2.4.3\build\Baseclass.Contrib.Nuget.Output.targets(65,5): error MSB4018:    at System.IO.Directory.EnumerateFiles(String path, String searchPattern, SearchOption searchOption)
42>E:\KK\src\.packages\Baseclass.Contrib.Nuget.Output.2.4.3\build\Baseclass.Contrib.Nuget.Output.targets(65,5): error MSB4018:    at Baseclass.Contrib.Nuget.Output.Build.NugetPackageManager.GetFilteredProjectNugetPackages(NugetPackageSource currentNugetPackageSource, HashSet`1 usedNugetPackages)
42>E:\KK\src\.packages\Baseclass.Contrib.Nuget.Output.2.4.3\build\Baseclass.Contrib.Nuget.Output.targets(65,5): error MSB4018:    at Baseclass.Contrib.Nuget.Output.Build.NugetPackageManager.TryGetUsedPackagesDependendingOnNugetOutput(ITaskItem[]& packages)
42>E:\KK\src\.packages\Baseclass.Contrib.Nuget.Output.2.4.3\build\Baseclass.Contrib.Nuget.Output.targets(65,5): error MSB4018:    at Baseclass.Contrib.Nuget.Output.Build.PackageRetrievalTask.Execute()
42>E:\KK\src\.packages\Baseclass.Contrib.Nuget.Output.2.4.3\build\Baseclass.Contrib.Nuget.Output.targets(65,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
42>E:\KK\src\.packages\Baseclass.Contrib.Nuget.Output.2.4.3\build\Baseclass.Contrib.Nuget.Output.targets(65,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
`

**Comment by Ruslan-B** [comment]
I also notised same thing, this version of nuget.config not working for me (same error):
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <config>
    <add key="repositorypath" value="../Packages" />
  </config>
</configuration>
```
but this one does:
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <settings>
    <repositoryPath>../Packages</repositoryPath>
  </settings>
</configuration>```
