### ISSUE TITLE
Unable to build the project after adding this nuget package

### ISSUE THREAD

**Issue by blueelvis** [baseclass/Contrib.Nuget#62]
Hi!

I am getting the following error saying that the key has already been added. Please find the logs below -
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4018	The "PackageRetrievalTask" task failed unexpectedly.
System.ArgumentException: Item has already been added. Key in dictionary: 'packageIcon.png'  Key being added: 'packageIcon.png'
   at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
   at System.Collections.Hashtable.Add(Object key, Object value)
   at System.Collections.Specialized.OrderedDictionary.Add(Object key, Object value)
   at MS.Internal.IO.Zip.ZipIOCentralDirectoryBlock.ParseRecord(BinaryReader reader, Int64 centralDirectoryOffset, Int32 centralDirectoryCount, Int64 expectedCentralDirectorySize)
   at MS.Internal.IO.Zip.ZipIOCentralDirectoryBlock.SeekableLoad(ZipIOBlockManager blockManager)
   at MS.Internal.IO.Zip.ZipIOBlockManager.get_CentralDirectoryBlock()
   at MS.Internal.IO.Zip.ZipArchive.GetFiles()
   at System.IO.Packaging.ZipPackage.ContentTypeHelper..ctor(ZipArchive zipArchive, IgnoredItemHelper ignoredItemHelper)
   at System.IO.Packaging.ZipPackage..ctor(String path, FileMode mode, FileAccess access, FileShare share, Boolean streaming)
   at System.IO.Packaging.Package.Open(String path, FileMode packageMode, FileAccess packageAccess, FileShare packageShare, Boolean streaming)
   at Baseclass.Contrib.Nuget.Output.Build.NugetPackageManager.TryGetUsedPackagesDependendingOnNugetOutput(ITaskItem[]& packages)
   at Baseclass.Contrib.Nuget.Output.Build.PackageRetrievalTask.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	CP	C:\Users\User\.nuget\packages\baseclass.contrib.nuget.output\2.4.3\build\Baseclass.Contrib.Nuget.Output.targets	65	
```

Any idea what might be the issue?

Thanks!

**Comment by romerod** [comment]
Does that icon file exist multiple times?

Holen Sie sich Outlook für Android<https://aka.ms/ghei36>

________________________________

**Comment by blueelvis** [comment]
@romerod - Yep! I deleted those files from the packages folder as well (Using Dotnet Core 3.0) but still the same error has happening. I have zeroed the error to this line -
```
usedPackages.Add($"{id}.{version}".ToLowerInvariant());
```

But that file exists across various packages and not just 1 single package.
